### ISSUE TITLE
Additional external resources within the template

### ISSUE THREAD

**Issue by pjotrsavitski** [centre-for-educational-technology/la_pills#8]
Current code allows using certain special notation within **descriptions** of activities. Currently handled ones include `{{website}}, {{dashboard}}, {{Q1}}, {{Q2}} ...` that are being generated by the system and automatically replaced.

It might be useful to allow creator defining additional external resources to be replaced within the texts. This should allow the system to link to those even if the HTML input is not allowed.

## Proposed logic

Resources should reside within the **resources** key of the general **Session Template** **context** structural element. The key should have an array of objects, empty array or even a missing key.

The structure should be as follows:

```
context:
  title: title
  ...
  resources:
    -
      key: weburl
      url: https://weburl.url
      text: Web URL
```

This would allow the `{{weburl}}` to be referenced from within the texts and replaced with an anchor that would look similar to this:
`<a href="URL" target="_blank">TEXT</a>`

The **text** could be made optional with either **key** or **url** being used instead.
